## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject:
  # @apidevtools/json-schema-ref-parser v15+ is ESM-only ("type": "module").
  # This project uses CommonJS require() in src/lib/openApiMockGenerator.js.
  # Upgrading would require migrating the entire project to ESM or using dynamic imports.
  # Migrate to ESM when the project is ready for a major version bump.
  - '@apidevtools/json-schema-ref-parser'
